# Generated by Django 5.0.3 on 2024-04-24 22:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="genre",
            field=models.CharField(
                default=1, max_length=100, verbose_name="жанр книги"
            ),
            preserve_default=False,
        ),
    ]
